### ISSUE TITLE
Verificação de Conformidade do Cliente SNTP

### ISSUE THREAD

**Issue by lramon2001** [lramon2001/Trabalho-01---SNTP#1]
Analisar se o cliente SNTP implementado atende às exigências e restrições especificadas pelo professor.

Critério de Aceitação: A issue será encerrada com uma resposta que detalhe se o cliente está em conformidade,ou não,com os requisitos, incluindo justificativas.

Tarefas:

-Comparar a implementação com os requisitos do professor.
-Documentar a conformidade ou desvios encontrados.
-Sugerir correções se necessário.

**Comment by Amandaaaaabreu** [comment]
Após compilar o programa, foram analisados alguns pontos:

1. Foram identificados warnings indicando que há módulos não utilizados no código.
2. Foi necessário realizar a instalação do pacote cargo usando o comando sudo apt install cargo, o que não está mencionado no arquivo README.
3. O teste de validação de IP também foi executado. Quando testado com uma sequência que não segue o formato de um IP, é exibido um erro específico. Já ao testar com um IP inválido, mas que respeita o formato padrão, a resposta foi a esperada.
4. Foi observado que a documentação do projeto está faltando.
